<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CK.Testing.NUnit" Version="15.0.4" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\..\CK.Packaging.Abstractions\CK.Packaging.Abstractions.csproj" />
    </ItemGroup>

</Project>
